### ISSUE TITLE
Auto-delete posts when spammed

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/scratch-spam#1]
Could you make it delete comments from non-trusted users whenever the comment rate is at least 5 times normal, then make an API so people just have to @ their bot to add someone to their trusted list?

**Comment by webdev03** [comment]
Why an API? Automatic reporting is too overpowered but automatic deletion is something that I can consider. One thing though, I really need help on the HTML parser for comments

**Comment by hello-smile6** [comment]
> Why an API? Automatic reporting is too overpowered but automatic deletion is something that I can consider. One thing though, I really need help on the HTML parser for comments

Seems like that's a bit hard. https://github.com/The-Cloud-Dev/scratch2py/blob/main/scratch2py/__init__.py#L353-L369 Scratch2py can't even do it. You could ask `@SheepTester` for help, maybe. Also, maybe look at how Scratch Addons does it. If the scratchdb backend's open-source, that could even be a good place to look. Maybe just read the user's messages, then you could act at a user level.

**Comment by webdev03** [comment]
I'll look into how nono word does it.

**Comment by hello-smile6** [comment]
> I'll look into how nono word does it.

If that won't work, could you just read the messages? Also, could you add a whitelist feature where the user just has to comment on a project or something?

**Comment by webdev03** [comment]
https://github.com/INSERT_NONOWORD_ORG/INSERT_NONOWORD_REPO/blob/bf470f18eb1ebd3e59947511a61229c847e6492c/popups/scratch-messaging/api.js#L50

**Comment by hello-smile6** [comment]
> https://github.com/INSERT_NONOWORD_ORG/INSERT_NONOWORD_REPO/blob/bf470f18eb1ebd3e59947511a61229c847e6492c/popups/scratch-messaging/api.js#L50

Just use the SHA512 hash. 930c8ef7c39f640fb2fb6d60dd0cafe8252c3353fdf059242ef25dae527dc59189544f876977419757b0d12963e0e3f7bfbc46f6ac29123bbf09cb91bdd56b48

**Comment by webdev03** [comment]
It's done!

**Comment by hello-smile6** [comment]
> It's done!

Awesome!
