### ISSUE TITLE
Use profanity list

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/scratch-spam#12]
Messages containing profanity need deleted immediately. Even if you're not comfortable with using a filtering package on the actual repository, you could always use Replit and store the name of your package in an environment variable, then run a server from `/tmp`.

**Comment by webdev03** [comment]
Profanity filter is handled by Scratch already.

**Comment by hello-smile6** [comment]
> Profanity filter is handled by Scratch already.

But they still missed that F attack. Shouldn't you strip non-UTF-8 characters and check then?

**Comment by webdev03** [comment]
If they contain those characters it's likely they're already attempting to do this. Also, people are encouraged to change the disallow list

**Comment by hello-smile6** [comment]
> If they contain those characters it's likely they're already attempting to do this. Also, people are encouraged to change the disallow list

Good point. You might want to normalize homographs before processing.
