### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Quantum-Codes** [webdev03/scratch-spam#16]
Make a comment on their profile (with their own account) to show that it has deleted it. 

This will prevent problems when the user doesn't know if deleted cuz of cache or whatever(mentioned in README)

**Comment by Quantum-Codes** [comment]
> Making a comment is banned I think.

No... it's allowed. Just don't spam

**Comment by webdev03** [comment]
I asked in the forums once, everyone said even 1 comment is not allowed.

**Comment by Quantum-Codes** [comment]
Oh... I have seen people making multiple ones (even I made >2)

Can u give the link of that forum?

**Comment by webdev03** [comment]
I don't have it right now

**Comment by Quantum-Codes** [comment]
Ok np. Better don't add then
