### ISSUE TITLE
Known spammers

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/scratch-spam#5]
Here's a list of users to automatically delete comments from.

- [ ]  [@mcnetweb_](https://scratch.mit.edu/users/mcnetweb_) [(Targeted @griffpatch )](https://scratch.mit.edu/users/griffpatch/#comments-181342116)

I'll add more as I find them.

**Comment by webdev03** [comment]
How did you find!??!?!!?

**Comment by hello-smile6** [comment]
> How did you find!??!?!!?

Scrolled down on their comments.

**Comment by hello-smile6** [comment]
That user may be legitimate, it may have been a family member of those, but that should become clear soon. If someone's comments go down and people get mad at them, it's probably them.

**Comment by hello-smile6** [comment]
@Chiroyce1 Who spammed on your account?

**Comment by hello-smile6** [comment]
> How did you find!??!?!!?

That was a recent one, only 3 hours ago, and probably a false positive.

**Comment by webdev03** [comment]
Oh ok

**Comment by hello-smile6** [comment]
https://scratch.mit.edu/users/griffpatch/#comments-181343353 (`@ejcorter`) with letter spam
https://scratch.mit.edu/users/griffpatch/#comments-181342116 (`@mcnetweb_`) with gross "toes" spam, some content implies >18 meaning
I'd say `@mcnetweb_` is a more firm candidate for known spammers.

**Comment by webdev03** [comment]
That'd be name and shaming, actually. May implement it later. Please don't take this as an insult, or me not accepting your contributions. I'll decide on it later.
