### ISSUE TITLE
Automatic delete?

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/scratch-spam#8]
How will it delete comments in the background?

**Comment by webdev03** [comment]
It just uses the deleteComment in the ScratchSession class

**Comment by hello-smile6** [comment]
> It just uses the deleteComment in the ScratchSession class

Okay! Spam my profile, I wanna test this.

**Comment by webdev03** [comment]
Just put empty comments. Right now it also deletes comments you make.

**Comment by hello-smile6** [comment]
> Just put empty comments. Right now it also deletes comments you make.

Could you spam mine? I'll set it to remove U+2022 (bullet point)

**Comment by hello-smile6** [comment]
@webdev03 jQuery gets stuck in vim the most. https://stackoverflow.blog/2017/05/23/stack-overflow-helping-one-million-developers-exit-vim/

**Comment by webdev03** [comment]
I am not spamming yours. I only spam accounts I own. Just comment like 6 ones with an empty space. It works.

**Comment by hello-smile6** [comment]
> I am not spamming yours. I only spam accounts I own. Just comment like 6 ones with an empty space. It works.

Could you give me a demo with a video recording?

**Comment by hello-smile6** [comment]
@webdev03 Or, could I spam your account for you???

**Comment by hello-smile6** [comment]
@webdev03 https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#0

**Comment by webdev03** [comment]
> @webdev03 https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#0

Nice! I'll look into it later.

**Comment by hello-smile6** [comment]
> > @webdev03 https://developers.google.com/codelabs/tensorflowjs-comment-spam-detection#0
> 
> Nice! I'll look into it later.

Does `process.env` work?

**Comment by webdev03** [comment]
`process.env` works, for replit too. It loads with the `dotenv` library

**Comment by hello-smile6** [comment]
> `process.env` works, for replit too. It loads with the `dotenv` library if you have `.env` file, and it also fallbacks to process.env

Good.

**Comment by hello-smile6** [comment]
#9

**Comment by webdev03** [comment]
Does it work?

**Comment by hello-smile6** [comment]
> Does it work?

What?

**Comment by webdev03** [comment]
> How will it delete comments in the background?

**Comment by hello-smile6** [comment]
> > How will it delete comments in the background?

What?

**Comment by webdev03** [comment]
Focus not clear - closing for now...
